config/routes.rb
Rails.application.routes.draw do
  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'home/index'
  post 'home/create'
  get 'home/search'
  get '/friend/myfriend' => 'friend#myfriend'
  get '/friend/f_request' => 'friend#f_request'
  get '/friend/f_accept' => 'friend#f_accept'
  post '/friend/search' => 'friend#search'
  post '/friend/myfriend'
  get '/friend/search'
  get '/friend/f_decline' => 'friend#f_decline'
  get 'edit/:id' => 'home#edit'
  get 'destroy/:id' => 'home#destroy'
  patch 'update/:id' => 'home#update'

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    unless user_signed_in?
      redirect_to '/users/sign_in'
    end
   # @user=User.new
    @post=Post.new
    @posts=Post.all
    #@posts = Project.search(params[:search])
  end
 # def search
  #      @posts = Post.all
   #     if params[:search]
    #        @posts=Post.search(params[:search]).order("created_at DESC")
     #   end
#  end
    
  def create
    @post = Post.new(post_params)
    @post.save
   
    redirect_to :back
  end
  
  def edit
    @post = Post.find(params[:id])
    authorize @post, :update?
  end
  
  def update
     @post = Post.find(params[:id])
    authorize @post, :update?
    @post.update(update_params)
    
    redirect_to "/home/index"
  end

  def destroy
    @post = Post.find(params[:id])
    authorize @post, :update?
    @post.destroy
    redirect_to :back
  end
  
  private
  def post_params
    params.require(:post).permit(:title, :content, :user_id, :scope)
  end
  
  def update_params
    params.require(:post).permit(:title, :content, :scope)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/edit.erb
<div class="bg" style="margin-top: 20px; margin-left: 100px; margin-right: 100px">
  <h4 ><p><%= current_user.email %>
  <%= current_user.nickname %>님, 환영합니다.
  <%= link_to '로그아웃', destroy_user_session_path, method: :get, data: {confirm: '로그아웃합니다'} %></p>
  <%= link_to '친구찾기', friend_myfriend_path, method: :get %></p></h4>

  <div class="posting" style="margin-top: 20px; margin-left: 150px; margin-right: 150px">
    <%= form_for @post, url: {action: "update"} do |f| %>
      <%= f.text_field :title, size: 100, maxlength: 135 %>
      <%= f.text_field :content, size: 100 %>
      <label><%= f.radio_button :scope, 1 %> 비공개</label>
      <label><%= f.radio_button :scope, 2 %> 친구 공개</label>
      <label><%= f.radio_button :scope, 3 %> 전체 공개</label>
      <%= f.submit '전송' %>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<p id="notice"><%= notice %></p>
<div class="container">
  <h4>해시태그를 찾아 볼까요</h4>
    <form action='hashtags' method='get'>
    <input type="text" name="search_hash">
    <button type="submit">검색</button>
    </form><hr>
</div>
<div class="container">
  <%= form_for @post, url: {action: "create"} do |p| %>
    <%= p.hidden_field :user_id, value: current_user.id %>
    <%= p.text_field :title %><br />
    <%= p.text_area :content, size: "60*12" %><br />
    <label><%= p.radio_button :scope, 1 %> 비공개</label>
    <label><%= p.radio_button :scope, 2 %> 친구 공개</label>
    <label><%= p.radio_button :scope, 3 %> 전체 공개</label>
    <%= p.submit "create" %>
   
  <% end %>
  <br />
 <% @posts.each do |f| %>
    <% if current_user.read_authority?(f) %>
      <strong>NICKNAME: </strong><%= f.user.nickname %><br /> <!---nickname은-->
      <strong>TITLE: </strong><%= f.title %><br />
      <strong>CONTENT WITH HASHTAG: </strong><%= linkify_hashtags(f.content)%><br />
      <% if policy(f).update? %>
      <a href="/edit/<%= f.id %>">[수정]</a>
      <a href="/destroy/<%= f.id %>">[삭제]</a>
      <hr>
      <% else %>
      <hr>
      <% end %>
    <% end %>
  <% end %>
  
  <br />
  <%= link_to 'make friends', friend_myfriend_path, method: :get %>
</div>