config/routes.rb
Rails.application.routes.draw do
  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'home/index'
  post 'home/create'
  get 'home/search'
  get '/friend/myfriend' => 'friend#myfriend'
  get '/friend/f_request' => 'friend#f_request'
  get '/friend/f_accept' => 'friend#f_accept'
  post '/friend/search' => 'friend#search'
  post '/friend/myfriend'
  get '/friend/search'
  get '/friend/f_decline' => 'friend#f_decline'
  get 'edit/:id' => 'home#edit'
  get 'destroy/:id' => 'home#destroy'
  patch 'update/:id' => 'home#update'

  root 'home#index'

end

app/controllers/friend_controller.rb
class FriendController < ApplicationController
    def myfriend
        @friend = User.find_by_nickname(params[:friend])
        @friends = current_user.friends
        @users = User.all
        @requested = current_user.requested_friends
    end
    
    def search
        @users = User.all
        if params[:search]
            @users=User.search(params[:search]).order("created_at DESC")
        end
    end
    
    def result
    end

    def f_request
        @current_user=current_user
        @friend = User.find_by_nickname(params[:friend])
        current_user.friend_request(@friend)
        redirect_to '/friend/myfriend'
    end

    def f_accept
        @current_user=current_user
        @friend = User.find_by_nickname(params[:friend])
        current_user.accept_request(@friend)
        redirect_to '/friend/myfriend'
    end

    def f_decline
       
        @friend = User.find_by_nickname(params[:friend])
        current_user.decline_request(@friend)
        redirect_to '/friend/myfriend'
    end
end

app/helpers/friend_helper.rb
module FriendHelper
end

app/views/friend/myfriend.erb
<br />
Every Members<br /><hr />
<% @users.each do |u| %>
<%= u.nickname %>
<form action="/friend/f_request" method="get">
    <% if current_user.pending_friends.include?(u) %>
        <h5>이미친구가되엇오요</h5>
    <% else %>
    <% unless current_user.id == u.id %>
         <input type="hidden" name="friend" value="<%= u.nickname %>">
    <button type="submit">friend ok</button>
    <% end %>
    <% end %>
</form>
<% end %>
<br />


<hr />
Friend List<br />
<% @requested.each do |r| %>
    <%= r.nickname %>
    <form action="/friend/f_accept" method="get">
        <input type="hidden" name="friend" value="<%= r.nickname %>">
        <button type="submit">accept</button>
    </form>
    <form action="/friend/f_decline" method="get">
        <input type="hidden" name="friend" value="<%= r.nickname %>">
        <button type="submit">decline</button>
    </form>
   
<% end %>
<% @friends.each do |f| %>
<%= f.nickname %>
<br />
<% end %>
<%= link_to 'search friends', friend_search_path, method: :post %>

app/views/friend/search.erb
<form action="/friend/search" method="post">
    <input type="text" name="search">
    <button type="submit">검색</button>
</form>
    
<% if @users %>
    Let you see<br />
    <% @users.each do |us| %>
        <%= us.nickname %><br />
    <% end %>
<% end %>